export const SharePointServicePrincipal = '00000003-0000-0ff1-ce00-000000000000';
export const HighTrustTokenLifeTime: number = 12 * 60 * 60;
export const MSOnlineSts = 'https://login.microsoftonline.com/extSTS.srf';
export const FbaAuthEndpoint = '_vti_bin/authentication.asmx';
export const TmgAuthEndpoint = 'CookieAuth.dll?Logon';
export const FormsPath = '_forms/default.aspx?wa=wsignin1.0';
export const RtFa = 'rtFa';
export const FedAuth = 'FedAuth';
export const AdfsOnlineRealm = 'urn:federation:MicrosoftOnline';
export const OnlineUserRealmEndpoint = 'https://login.microsoftonline.com/GetUserRealm.srf';
